{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "39e6dbaa-2e93-4749-b5ae-892b04b0e783",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: tensorflow==2.15.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (2.15.0)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (1.4.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (1.6.3)\n",
      "Requirement already satisfied: flatbuffers>=23.5.26 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow==2.15.0) (24.3.7)\n",
      "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (0.4.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (0.2.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow==2.15.0) (3.10.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (16.0.0)\n",
      "Requirement already satisfied: ml-dtypes~=0.2.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow==2.15.0) (0.2.0)\n",
      "Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow==2.15.0) (1.26.4)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (3.3.0)\n",
      "Requirement already satisfied: packaging in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (23.0)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow==2.15.0) (4.25.3)\n",
      "Requirement already satisfied: setuptools in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (67.6.1)\n",
      "Requirement already satisfied: six>=1.12.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (1.16.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (2.2.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (4.5.0)\n",
      "Requirement already satisfied: wrapt<1.15,>=1.11.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (1.14.1)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorflow==2.15.0) (0.32.0)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow==2.15.0) (1.62.1)\n",
      "Requirement already satisfied: tensorboard<2.16,>=2.15 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow==2.15.0) (2.15.2)\n",
      "Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow==2.15.0) (2.15.0)\n",
      "Requirement already satisfied: keras<2.16,>=2.15.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow==2.15.0) (2.15.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow==2.15.0) (0.40.0)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2.17.1)\n",
      "Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (1.0.0)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.4.3)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2.31.0)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (0.7.2)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2.2.3)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (5.3.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (0.2.8)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (4.9)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (1.3.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2022.12.7)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2.1.2)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (0.4.8)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /geode2/soft/hps/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.2.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install --upgrade tensorflow==2.15.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ef941c0f-35c5-4177-8615-5a8189421f5d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Python 3.10.10\n"
     ]
    }
   ],
   "source": [
    "!python --version"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a79a929b-5272-41a8-a315-f54bab5d9130",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Num GPUs Available:  1\n",
      "TensorFlow will run on GPU.\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "\n",
    "print(\"Num GPUs Available: \", len(tf.config.list_physical_devices('GPU')))\n",
    "if tf.config.list_physical_devices('GPU'):\n",
    "    print(\"TensorFlow will run on GPU.\")\n",
    "else:\n",
    "    print(\"TensorFlow will run on CPU.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "f2198dd6-1c59-4228-9aab-a08c191d1d06",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "nvcc: NVIDIA (R) Cuda compiler driver\n",
      "Copyright (c) 2005-2022 NVIDIA Corporation\n",
      "Built on Tue_May__3_18:49:52_PDT_2022\n",
      "Cuda compilation tools, release 11.7, V11.7.64\n",
      "Build cuda_11.7.r11.7/compiler.31294372_0\n"
     ]
    }
   ],
   "source": [
    "!nvcc --version"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "0dd81d4e-fcbe-4e06-ab3f-fb61f2da43e9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    age  hypertension  heart_disease    bmi  HbA1c_level  blood_glucose_level  \\\n",
      "0  80.0             0              1  25.19          6.6                  140   \n",
      "1  54.0             0              0  27.32          6.6                   80   \n",
      "2  28.0             0              0  27.32          5.7                  158   \n",
      "3  36.0             0              0  23.45          5.0                  155   \n",
      "4  76.0             1              1  20.14          4.8                  155   \n",
      "\n",
      "   diabetes  gender_Female  gender_Male  gender_Other  \\\n",
      "0         0              1            0             0   \n",
      "1         0              1            0             0   \n",
      "2         0              0            1             0   \n",
      "3         0              1            0             0   \n",
      "4         0              0            1             0   \n",
      "\n",
      "   smoking_history_No Info  smoking_history_current  smoking_history_former  \\\n",
      "0                        0                        0                       0   \n",
      "1                        1                        0                       0   \n",
      "2                        0                        0                       0   \n",
      "3                        0                        1                       0   \n",
      "4                        0                        1                       0   \n",
      "\n",
      "   smoking_history_never  smoking_history_not current  \n",
      "0                      1                            0  \n",
      "1                      0                            0  \n",
      "2                      1                            0  \n",
      "3                      0                            0  \n",
      "4                      0                            0  \n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Load the dataset\n",
    "data_path = '../data/processed/cleaned_diabetes_one_hot_encoding.csv'\n",
    "df = pd.read_csv(data_path)\n",
    "\n",
    "# Display the first few rows of the dataframe\n",
    "print(df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "39af0974-0f10-4cf8-9292-b6a0e04e758c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Normalizing the data\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "\n",
    "features = df.drop('diabetes', axis=1).columns.tolist()\n",
    "scaler = MinMaxScaler()\n",
    "\n",
    "df[features] = scaler.fit_transform(df[features])\n",
    "\n",
    "# Reshape data for LTSM\n",
    "X = df.drop('diabetes', axis=1).values\n",
    "Y = df['diabetes'].values\n",
    "\n",
    "# Reshape X to be [samples, timesteps, features]\n",
    "X = X.reshape((X.shape[0], 1, X.shape[1]))\n",
    "\n",
    "# Splitting the dataset\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "eb00eee1-ca32-4551-b553-1cb86c5de6f9",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# Build the LSTM Model\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import LSTM, Dense, BatchNormalization, Dropout\n",
    "from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "model = Sequential()\n",
    "model.add(LSTM(50, input_shape=(X_train.shape[1], X_train.shape[2])))\n",
    "model.add(Dense(1, activation='sigmoid'))\n",
    "\n",
    "model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "576ddd5c-0c7e-4dd9-a31e-659afa432216",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/100\n"
     ]
    },
    {
     "ename": "UnknownError",
     "evalue": "Graph execution error:\n\nDetected at node CudnnRNN defined at (most recent call last):\n<stack traces unavailable>\nFail to find the dnn implementation.\n\t [[{{node CudnnRNN}}]]\n\t [[sequential/lstm/PartitionedCall]] [Op:__inference_train_function_3334]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnknownError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[8], line 8\u001b[0m\n\u001b[1;32m      5\u001b[0m model\u001b[38;5;241m.\u001b[39mcompile(loss\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mbinary_crossentropy\u001b[39m\u001b[38;5;124m'\u001b[39m, optimizer\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124madam\u001b[39m\u001b[38;5;124m'\u001b[39m, metrics\u001b[38;5;241m=\u001b[39m[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124maccuracy\u001b[39m\u001b[38;5;124m'\u001b[39m, Precision(), Recall()])\n\u001b[1;32m      7\u001b[0m \u001b[38;5;66;03m# Train the model (ensure you have trained your model with these metrics before evaluating)\u001b[39;00m\n\u001b[0;32m----> 8\u001b[0m history \u001b[38;5;241m=\u001b[39m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m      9\u001b[0m \u001b[43m    \u001b[49m\u001b[43mX_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mY_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     10\u001b[0m \u001b[43m    \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m100\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     11\u001b[0m \u001b[43m    \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m64\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     12\u001b[0m \u001b[43m    \u001b[49m\u001b[43mvalidation_split\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m0.2\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     13\u001b[0m \u001b[43m    \u001b[49m\u001b[43mverbose\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m2\u001b[39;49m\n\u001b[1;32m     14\u001b[0m \u001b[43m)\u001b[49m\n\u001b[1;32m     16\u001b[0m \u001b[38;5;66;03m# Evaluate the model on the test set with additional metrics\u001b[39;00m\n\u001b[1;32m     17\u001b[0m loss, accuracy, precision, recall \u001b[38;5;241m=\u001b[39m model\u001b[38;5;241m.\u001b[39mevaluate(X_test, Y_test, verbose\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m2\u001b[39m)\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mUnknownError\u001b[0m: Graph execution error:\n\nDetected at node CudnnRNN defined at (most recent call last):\n<stack traces unavailable>\nFail to find the dnn implementation.\n\t [[{{node CudnnRNN}}]]\n\t [[sequential/lstm/PartitionedCall]] [Op:__inference_train_function_3334]"
     ]
    }
   ],
   "source": [
    "from tensorflow.keras.metrics import Precision, Recall\n",
    "from sklearn.metrics import classification_report, roc_auc_score\n",
    "\n",
    "# Add precision and recall to the model's metrics\n",
    "model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', Precision(), Recall()])\n",
    "\n",
    "# Train the model (ensure you have trained your model with these metrics before evaluating)\n",
    "history = model.fit(\n",
    "    X_train, Y_train, \n",
    "    epochs=100, \n",
    "    batch_size=64, \n",
    "    validation_split=0.2, \n",
    "    verbose=2\n",
    ")\n",
    "\n",
    "# Evaluate the model on the test set with additional metrics\n",
    "loss, accuracy, precision, recall = model.evaluate(X_test, Y_test, verbose=2)\n",
    "print(f'Test Accuracy: {accuracy*100:.2f}%')\n",
    "print(f'Precision: {precision:.2f}')\n",
    "print(f'Recall: {recall:.2f}')\n",
    "\n",
    "# For F1-score and ROC-AUC, use sklearn's utilities as they're not directly supported as Keras metrics during training\n",
    "from sklearn.metrics import f1_score, roc_auc_score\n",
    "\n",
    "# Predict probabilities for ROC AUC\n",
    "y_probs = model.predict(X_test)[:, 0]  # assuming your model outputs probabilities for class 1\n",
    "\n",
    "# Predict class labels for F1 score and other metrics\n",
    "y_pred = (y_probs > 0.5).astype('int32')\n",
    "\n",
    "# Calculate F1 score\n",
    "f1 = f1_score(Y_test, y_pred)\n",
    "print(f'F1 Score: {f1:.2f}')\n",
    "\n",
    "# Calculate ROC AUC Score\n",
    "roc_auc = roc_auc_score(Y_test, y_probs)\n",
    "print(f'ROC AUC Score: {roc_auc:.2f}')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "faba948c",
   "metadata": {},
   "source": [
    "##### Refined LTSM Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "fd761700",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/100\n",
      "\n",
      "Epoch 1: val_loss improved from inf to 0.10909, saving model to best_model.keras\n",
      "893/893 - 6s - 7ms/step - accuracy: 0.9494 - loss: 0.1641 - val_accuracy: 0.9644 - val_loss: 0.1091\n",
      "Epoch 2/100\n",
      "\n",
      "Epoch 2: val_loss improved from 0.10909 to 0.10535, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9605 - loss: 0.1190 - val_accuracy: 0.9653 - val_loss: 0.1054\n",
      "Epoch 3/100\n",
      "\n",
      "Epoch 3: val_loss improved from 0.10535 to 0.10230, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9617 - loss: 0.1154 - val_accuracy: 0.9662 - val_loss: 0.1023\n",
      "Epoch 4/100\n",
      "\n",
      "Epoch 4: val_loss improved from 0.10230 to 0.10195, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9622 - loss: 0.1135 - val_accuracy: 0.9655 - val_loss: 0.1020\n",
      "Epoch 5/100\n",
      "\n",
      "Epoch 5: val_loss improved from 0.10195 to 0.10139, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9623 - loss: 0.1125 - val_accuracy: 0.9664 - val_loss: 0.1014\n",
      "Epoch 6/100\n",
      "\n",
      "Epoch 6: val_loss did not improve from 0.10139\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9628 - loss: 0.1102 - val_accuracy: 0.9655 - val_loss: 0.1027\n",
      "Epoch 7/100\n",
      "\n",
      "Epoch 7: val_loss did not improve from 0.10139\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9628 - loss: 0.1094 - val_accuracy: 0.9653 - val_loss: 0.1023\n",
      "Epoch 8/100\n",
      "\n",
      "Epoch 8: val_loss improved from 0.10139 to 0.09914, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9633 - loss: 0.1074 - val_accuracy: 0.9664 - val_loss: 0.0991\n",
      "Epoch 9/100\n",
      "\n",
      "Epoch 9: val_loss did not improve from 0.09914\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9627 - loss: 0.1088 - val_accuracy: 0.9660 - val_loss: 0.1001\n",
      "Epoch 10/100\n",
      "\n",
      "Epoch 10: val_loss improved from 0.09914 to 0.09886, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9635 - loss: 0.1062 - val_accuracy: 0.9654 - val_loss: 0.0989\n",
      "Epoch 11/100\n",
      "\n",
      "Epoch 11: val_loss improved from 0.09886 to 0.09717, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9639 - loss: 0.1063 - val_accuracy: 0.9658 - val_loss: 0.0972\n",
      "Epoch 12/100\n",
      "\n",
      "Epoch 12: val_loss improved from 0.09717 to 0.09538, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9646 - loss: 0.1044 - val_accuracy: 0.9676 - val_loss: 0.0954\n",
      "Epoch 13/100\n",
      "\n",
      "Epoch 13: val_loss did not improve from 0.09538\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9655 - loss: 0.1020 - val_accuracy: 0.9659 - val_loss: 0.0975\n",
      "Epoch 14/100\n",
      "\n",
      "Epoch 14: val_loss improved from 0.09538 to 0.08835, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9665 - loss: 0.0991 - val_accuracy: 0.9707 - val_loss: 0.0883\n",
      "Epoch 15/100\n",
      "\n",
      "Epoch 15: val_loss improved from 0.08835 to 0.08510, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9681 - loss: 0.0962 - val_accuracy: 0.9732 - val_loss: 0.0851\n",
      "Epoch 16/100\n",
      "\n",
      "Epoch 16: val_loss improved from 0.08510 to 0.08378, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9691 - loss: 0.0933 - val_accuracy: 0.9728 - val_loss: 0.0838\n",
      "Epoch 17/100\n",
      "\n",
      "Epoch 17: val_loss improved from 0.08378 to 0.08121, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9697 - loss: 0.0919 - val_accuracy: 0.9738 - val_loss: 0.0812\n",
      "Epoch 18/100\n",
      "\n",
      "Epoch 18: val_loss improved from 0.08121 to 0.08038, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9694 - loss: 0.0916 - val_accuracy: 0.9739 - val_loss: 0.0804\n",
      "Epoch 19/100\n",
      "\n",
      "Epoch 19: val_loss did not improve from 0.08038\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9703 - loss: 0.0902 - val_accuracy: 0.9736 - val_loss: 0.0807\n",
      "Epoch 20/100\n",
      "\n",
      "Epoch 20: val_loss improved from 0.08038 to 0.07898, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9703 - loss: 0.0888 - val_accuracy: 0.9754 - val_loss: 0.0790\n",
      "Epoch 21/100\n",
      "\n",
      "Epoch 21: val_loss did not improve from 0.07898\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9703 - loss: 0.0890 - val_accuracy: 0.9736 - val_loss: 0.0803\n",
      "Epoch 22/100\n",
      "\n",
      "Epoch 22: val_loss did not improve from 0.07898\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9704 - loss: 0.0886 - val_accuracy: 0.9713 - val_loss: 0.0856\n",
      "Epoch 23/100\n",
      "\n",
      "Epoch 23: val_loss improved from 0.07898 to 0.07762, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9707 - loss: 0.0878 - val_accuracy: 0.9753 - val_loss: 0.0776\n",
      "Epoch 24/100\n",
      "\n",
      "Epoch 24: val_loss did not improve from 0.07762\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9711 - loss: 0.0866 - val_accuracy: 0.9756 - val_loss: 0.0779\n",
      "Epoch 25/100\n",
      "\n",
      "Epoch 25: val_loss did not improve from 0.07762\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9710 - loss: 0.0869 - val_accuracy: 0.9737 - val_loss: 0.0791\n",
      "Epoch 26/100\n",
      "\n",
      "Epoch 26: val_loss did not improve from 0.07762\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9709 - loss: 0.0869 - val_accuracy: 0.9739 - val_loss: 0.0793\n",
      "Epoch 27/100\n",
      "\n",
      "Epoch 27: val_loss did not improve from 0.07762\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9710 - loss: 0.0867 - val_accuracy: 0.9746 - val_loss: 0.0778\n",
      "Epoch 28/100\n",
      "\n",
      "Epoch 28: val_loss did not improve from 0.07762\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9716 - loss: 0.0860 - val_accuracy: 0.9728 - val_loss: 0.0817\n",
      "Epoch 29/100\n",
      "\n",
      "Epoch 29: val_loss improved from 0.07762 to 0.07744, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9712 - loss: 0.0856 - val_accuracy: 0.9739 - val_loss: 0.0774\n",
      "Epoch 30/100\n",
      "\n",
      "Epoch 30: val_loss did not improve from 0.07744\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9713 - loss: 0.0852 - val_accuracy: 0.9747 - val_loss: 0.0779\n",
      "Epoch 31/100\n",
      "\n",
      "Epoch 31: val_loss did not improve from 0.07744\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9718 - loss: 0.0850 - val_accuracy: 0.9737 - val_loss: 0.0786\n",
      "Epoch 32/100\n",
      "\n",
      "Epoch 32: val_loss did not improve from 0.07744\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9716 - loss: 0.0854 - val_accuracy: 0.9739 - val_loss: 0.0786\n",
      "Epoch 33/100\n",
      "\n",
      "Epoch 33: val_loss did not improve from 0.07744\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9710 - loss: 0.0854 - val_accuracy: 0.9744 - val_loss: 0.0777\n",
      "Epoch 34/100\n",
      "\n",
      "Epoch 34: val_loss did not improve from 0.07744\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9721 - loss: 0.0838 - val_accuracy: 0.9735 - val_loss: 0.0790\n",
      "Epoch 35/100\n",
      "\n",
      "Epoch 35: val_loss did not improve from 0.07744\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9718 - loss: 0.0846 - val_accuracy: 0.9744 - val_loss: 0.0790\n",
      "Epoch 36/100\n",
      "\n",
      "Epoch 36: val_loss improved from 0.07744 to 0.07724, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9717 - loss: 0.0843 - val_accuracy: 0.9749 - val_loss: 0.0772\n",
      "Epoch 37/100\n",
      "\n",
      "Epoch 37: val_loss improved from 0.07724 to 0.07651, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9717 - loss: 0.0836 - val_accuracy: 0.9753 - val_loss: 0.0765\n",
      "Epoch 38/100\n",
      "\n",
      "Epoch 38: val_loss improved from 0.07651 to 0.07633, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9717 - loss: 0.0842 - val_accuracy: 0.9757 - val_loss: 0.0763\n",
      "Epoch 39/100\n",
      "\n",
      "Epoch 39: val_loss improved from 0.07633 to 0.07626, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9720 - loss: 0.0840 - val_accuracy: 0.9751 - val_loss: 0.0763\n",
      "Epoch 40/100\n",
      "\n",
      "Epoch 40: val_loss did not improve from 0.07626\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9716 - loss: 0.0842 - val_accuracy: 0.9737 - val_loss: 0.0789\n",
      "Epoch 41/100\n",
      "\n",
      "Epoch 41: val_loss did not improve from 0.07626\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9721 - loss: 0.0841 - val_accuracy: 0.9758 - val_loss: 0.0763\n",
      "Epoch 42/100\n",
      "\n",
      "Epoch 42: val_loss did not improve from 0.07626\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9721 - loss: 0.0831 - val_accuracy: 0.9749 - val_loss: 0.0764\n",
      "Epoch 43/100\n",
      "\n",
      "Epoch 43: val_loss did not improve from 0.07626\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9717 - loss: 0.0837 - val_accuracy: 0.9740 - val_loss: 0.0802\n",
      "Epoch 44/100\n",
      "\n",
      "Epoch 44: val_loss improved from 0.07626 to 0.07608, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9721 - loss: 0.0835 - val_accuracy: 0.9758 - val_loss: 0.0761\n",
      "Epoch 45/100\n",
      "\n",
      "Epoch 45: val_loss did not improve from 0.07608\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9722 - loss: 0.0833 - val_accuracy: 0.9731 - val_loss: 0.0805\n",
      "Epoch 46/100\n",
      "\n",
      "Epoch 46: val_loss did not improve from 0.07608\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9726 - loss: 0.0827 - val_accuracy: 0.9758 - val_loss: 0.0761\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 47/100\n",
      "\n",
      "Epoch 47: val_loss did not improve from 0.07608\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9723 - loss: 0.0828 - val_accuracy: 0.9754 - val_loss: 0.0761\n",
      "Epoch 48/100\n",
      "\n",
      "Epoch 48: val_loss did not improve from 0.07608\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9723 - loss: 0.0827 - val_accuracy: 0.9758 - val_loss: 0.0765\n",
      "Epoch 49/100\n",
      "\n",
      "Epoch 49: val_loss improved from 0.07608 to 0.07557, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9723 - loss: 0.0832 - val_accuracy: 0.9758 - val_loss: 0.0756\n",
      "Epoch 50/100\n",
      "\n",
      "Epoch 50: val_loss did not improve from 0.07557\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9726 - loss: 0.0819 - val_accuracy: 0.9742 - val_loss: 0.0770\n",
      "Epoch 51/100\n",
      "\n",
      "Epoch 51: val_loss did not improve from 0.07557\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9729 - loss: 0.0823 - val_accuracy: 0.9760 - val_loss: 0.0757\n",
      "Epoch 52/100\n",
      "\n",
      "Epoch 52: val_loss did not improve from 0.07557\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9726 - loss: 0.0827 - val_accuracy: 0.9746 - val_loss: 0.0769\n",
      "Epoch 53/100\n",
      "\n",
      "Epoch 53: val_loss did not improve from 0.07557\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9727 - loss: 0.0824 - val_accuracy: 0.9757 - val_loss: 0.0757\n",
      "Epoch 54/100\n",
      "\n",
      "Epoch 54: val_loss did not improve from 0.07557\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9728 - loss: 0.0820 - val_accuracy: 0.9756 - val_loss: 0.0762\n",
      "Epoch 55/100\n",
      "\n",
      "Epoch 55: val_loss did not improve from 0.07557\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9722 - loss: 0.0820 - val_accuracy: 0.9746 - val_loss: 0.0775\n",
      "Epoch 56/100\n",
      "\n",
      "Epoch 56: val_loss improved from 0.07557 to 0.07522, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9730 - loss: 0.0817 - val_accuracy: 0.9760 - val_loss: 0.0752\n",
      "Epoch 57/100\n",
      "\n",
      "Epoch 57: val_loss did not improve from 0.07522\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9730 - loss: 0.0817 - val_accuracy: 0.9758 - val_loss: 0.0758\n",
      "Epoch 58/100\n",
      "\n",
      "Epoch 58: val_loss did not improve from 0.07522\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9731 - loss: 0.0816 - val_accuracy: 0.9740 - val_loss: 0.0766\n",
      "Epoch 59/100\n",
      "\n",
      "Epoch 59: val_loss did not improve from 0.07522\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9730 - loss: 0.0812 - val_accuracy: 0.9740 - val_loss: 0.0780\n",
      "Epoch 60/100\n",
      "\n",
      "Epoch 60: val_loss did not improve from 0.07522\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9730 - loss: 0.0815 - val_accuracy: 0.9752 - val_loss: 0.0763\n",
      "Epoch 61/100\n",
      "\n",
      "Epoch 61: val_loss improved from 0.07522 to 0.07494, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9729 - loss: 0.0815 - val_accuracy: 0.9753 - val_loss: 0.0749\n",
      "Epoch 62/100\n",
      "\n",
      "Epoch 62: val_loss improved from 0.07494 to 0.07486, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9728 - loss: 0.0817 - val_accuracy: 0.9763 - val_loss: 0.0749\n",
      "Epoch 63/100\n",
      "\n",
      "Epoch 63: val_loss did not improve from 0.07486\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9729 - loss: 0.0815 - val_accuracy: 0.9742 - val_loss: 0.0773\n",
      "Epoch 64/100\n",
      "\n",
      "Epoch 64: val_loss did not improve from 0.07486\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9730 - loss: 0.0812 - val_accuracy: 0.9743 - val_loss: 0.0770\n",
      "Epoch 65/100\n",
      "\n",
      "Epoch 65: val_loss improved from 0.07486 to 0.07475, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9729 - loss: 0.0817 - val_accuracy: 0.9759 - val_loss: 0.0747\n",
      "Epoch 66/100\n",
      "\n",
      "Epoch 66: val_loss did not improve from 0.07475\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9731 - loss: 0.0809 - val_accuracy: 0.9762 - val_loss: 0.0749\n",
      "Epoch 67/100\n",
      "\n",
      "Epoch 67: val_loss did not improve from 0.07475\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9731 - loss: 0.0813 - val_accuracy: 0.9755 - val_loss: 0.0757\n",
      "Epoch 68/100\n",
      "\n",
      "Epoch 68: val_loss did not improve from 0.07475\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9731 - loss: 0.0809 - val_accuracy: 0.9758 - val_loss: 0.0756\n",
      "Epoch 69/100\n",
      "\n",
      "Epoch 69: val_loss did not improve from 0.07475\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9731 - loss: 0.0808 - val_accuracy: 0.9763 - val_loss: 0.0749\n",
      "Epoch 70/100\n",
      "\n",
      "Epoch 70: val_loss improved from 0.07475 to 0.07460, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9730 - loss: 0.0803 - val_accuracy: 0.9760 - val_loss: 0.0746\n",
      "Epoch 71/100\n",
      "\n",
      "Epoch 71: val_loss did not improve from 0.07460\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9734 - loss: 0.0807 - val_accuracy: 0.9742 - val_loss: 0.0773\n",
      "Epoch 72/100\n",
      "\n",
      "Epoch 72: val_loss did not improve from 0.07460\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9735 - loss: 0.0802 - val_accuracy: 0.9751 - val_loss: 0.0758\n",
      "Epoch 73/100\n",
      "\n",
      "Epoch 73: val_loss did not improve from 0.07460\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9733 - loss: 0.0801 - val_accuracy: 0.9745 - val_loss: 0.0766\n",
      "Epoch 74/100\n",
      "\n",
      "Epoch 74: val_loss did not improve from 0.07460\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9736 - loss: 0.0803 - val_accuracy: 0.9762 - val_loss: 0.0747\n",
      "Epoch 75/100\n",
      "\n",
      "Epoch 75: val_loss improved from 0.07460 to 0.07433, saving model to best_model.keras\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9734 - loss: 0.0803 - val_accuracy: 0.9764 - val_loss: 0.0743\n",
      "Epoch 76/100\n",
      "\n",
      "Epoch 76: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9735 - loss: 0.0804 - val_accuracy: 0.9758 - val_loss: 0.0748\n",
      "Epoch 77/100\n",
      "\n",
      "Epoch 77: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9735 - loss: 0.0803 - val_accuracy: 0.9754 - val_loss: 0.0760\n",
      "Epoch 78/100\n",
      "\n",
      "Epoch 78: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9736 - loss: 0.0797 - val_accuracy: 0.9759 - val_loss: 0.0753\n",
      "Epoch 79/100\n",
      "\n",
      "Epoch 79: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9733 - loss: 0.0805 - val_accuracy: 0.9762 - val_loss: 0.0748\n",
      "Epoch 80/100\n",
      "\n",
      "Epoch 80: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9733 - loss: 0.0799 - val_accuracy: 0.9758 - val_loss: 0.0761\n",
      "Epoch 81/100\n",
      "\n",
      "Epoch 81: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9737 - loss: 0.0794 - val_accuracy: 0.9765 - val_loss: 0.0745\n",
      "Epoch 82/100\n",
      "\n",
      "Epoch 82: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9735 - loss: 0.0800 - val_accuracy: 0.9756 - val_loss: 0.0752\n",
      "Epoch 83/100\n",
      "\n",
      "Epoch 83: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9740 - loss: 0.0793 - val_accuracy: 0.9761 - val_loss: 0.0749\n",
      "Epoch 84/100\n",
      "\n",
      "Epoch 84: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9731 - loss: 0.0807 - val_accuracy: 0.9764 - val_loss: 0.0748\n",
      "Epoch 85/100\n",
      "\n",
      "Epoch 85: val_loss did not improve from 0.07433\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9739 - loss: 0.0799 - val_accuracy: 0.9755 - val_loss: 0.0755\n",
      "Epoch 85: early stopping\n",
      "Restoring model weights from the end of the best epoch: 75.\n",
      "558/558 - 1s - 1ms/step - accuracy: 0.9736 - loss: 0.0802\n",
      "Test Accuracy: 97.36%\n",
      "\u001b[1m558/558\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m1s\u001b[0m 1ms/step\n",
      "F1 Score: 0.79\n",
      "ROC AUC Score: 0.97\n"
     ]
    }
   ],
   "source": [
    "# Build the LSTM Model\n",
    "model = Sequential([\n",
    "    LSTM(50, input_shape=(X_train.shape[1], X_train.shape[2]), return_sequences=True),\n",
    "    BatchNormalization(),\n",
    "    Dropout(0.2),\n",
    "    LSTM(25),\n",
    "    Dropout(0.2),\n",
    "    Dense(1, activation='sigmoid')\n",
    "])\n",
    "\n",
    "model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
    "\n",
    "# Setup callbacks\n",
    "callbacks = [\n",
    "    EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1),\n",
    "    ModelCheckpoint('best_model.keras', monitor='val_loss', save_best_only=True, verbose=1)\n",
    "]\n",
    "\n",
    "# Train the model\n",
    "history = model.fit(\n",
    "    X_train, Y_train, \n",
    "    epochs=100, \n",
    "    batch_size=64, \n",
    "    validation_split=0.2, \n",
    "    callbacks=callbacks,\n",
    "    verbose=2\n",
    ")\n",
    "\n",
    "# Load the best model\n",
    "model.load_weights('best_model.keras')\n",
    "\n",
    "# Evaluate the model on the test set\n",
    "loss, accuracy = model.evaluate(X_test, Y_test, verbose=2)\n",
    "print(f'Test Accuracy: {accuracy*100:.2f}%')\n",
    "\n",
    "# Predict class labels for F1 score and other metrics\n",
    "y_probs = model.predict(X_test)[:, 0]\n",
    "y_pred = (y_probs > 0.5).astype('int32')\n",
    "\n",
    "# Calculate F1 score and ROC AUC Score\n",
    "f1 = f1_score(Y_test, y_pred)\n",
    "roc_auc = roc_auc_score(Y_test, y_probs)\n",
    "print(f'F1 Score: {f1:.2f}')\n",
    "print(f'ROC AUC Score: {roc_auc:.2f}')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "81618bfb",
   "metadata": {},
   "source": [
    "#### Handling Class Imbalance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "7578f559",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/100\n",
      "893/893 - 4s - 5ms/step - accuracy: 0.9060 - loss: 0.2169 - val_accuracy: 0.8864 - val_loss: 0.1953\n",
      "Epoch 2/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9001 - loss: 0.2044 - val_accuracy: 0.8941 - val_loss: 0.1863\n",
      "Epoch 3/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9005 - loss: 0.2014 - val_accuracy: 0.9049 - val_loss: 0.1695\n",
      "Epoch 4/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9014 - loss: 0.2038 - val_accuracy: 0.9037 - val_loss: 0.1729\n",
      "Epoch 5/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9015 - loss: 0.2008 - val_accuracy: 0.8880 - val_loss: 0.2002\n",
      "Epoch 6/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8971 - loss: 0.1979 - val_accuracy: 0.8984 - val_loss: 0.1925\n",
      "Epoch 7/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.9027 - loss: 0.1988 - val_accuracy: 0.8967 - val_loss: 0.1843\n",
      "Epoch 8/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8970 - loss: 0.1997 - val_accuracy: 0.8986 - val_loss: 0.1792\n",
      "Epoch 9/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8993 - loss: 0.1991 - val_accuracy: 0.8960 - val_loss: 0.1832\n",
      "Epoch 10/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8992 - loss: 0.1999 - val_accuracy: 0.8926 - val_loss: 0.1871\n",
      "Epoch 11/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8981 - loss: 0.1966 - val_accuracy: 0.8975 - val_loss: 0.1844\n",
      "Epoch 12/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8990 - loss: 0.1990 - val_accuracy: 0.8917 - val_loss: 0.1880\n",
      "Epoch 13/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8935 - loss: 0.1987 - val_accuracy: 0.8933 - val_loss: 0.1821\n",
      "Epoch 14/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8962 - loss: 0.1945 - val_accuracy: 0.9057 - val_loss: 0.1672\n",
      "Epoch 15/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8948 - loss: 0.1945 - val_accuracy: 0.8934 - val_loss: 0.1883\n",
      "Epoch 16/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8916 - loss: 0.1985 - val_accuracy: 0.8893 - val_loss: 0.1917\n",
      "Epoch 17/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8919 - loss: 0.1957 - val_accuracy: 0.8982 - val_loss: 0.1770\n",
      "Epoch 18/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8936 - loss: 0.1965 - val_accuracy: 0.8975 - val_loss: 0.1742\n",
      "Epoch 19/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8938 - loss: 0.1969 - val_accuracy: 0.8958 - val_loss: 0.1841\n",
      "Epoch 20/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8926 - loss: 0.1953 - val_accuracy: 0.8986 - val_loss: 0.1835\n",
      "Epoch 21/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8966 - loss: 0.1950 - val_accuracy: 0.9015 - val_loss: 0.1786\n",
      "Epoch 22/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8971 - loss: 0.1932 - val_accuracy: 0.8886 - val_loss: 0.1949\n",
      "Epoch 23/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8933 - loss: 0.1943 - val_accuracy: 0.8829 - val_loss: 0.2098\n",
      "Epoch 24/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8925 - loss: 0.1956 - val_accuracy: 0.9022 - val_loss: 0.1766\n",
      "Epoch 25/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8944 - loss: 0.1956 - val_accuracy: 0.9029 - val_loss: 0.1732\n",
      "Epoch 26/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8940 - loss: 0.1958 - val_accuracy: 0.8914 - val_loss: 0.1956\n",
      "Epoch 27/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8926 - loss: 0.1943 - val_accuracy: 0.8970 - val_loss: 0.1861\n",
      "Epoch 28/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8971 - loss: 0.1947 - val_accuracy: 0.8991 - val_loss: 0.1843\n",
      "Epoch 29/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8939 - loss: 0.1935 - val_accuracy: 0.8979 - val_loss: 0.1770\n",
      "Epoch 30/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8940 - loss: 0.1936 - val_accuracy: 0.8941 - val_loss: 0.1884\n",
      "Epoch 31/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8948 - loss: 0.1937 - val_accuracy: 0.9017 - val_loss: 0.1775\n",
      "Epoch 32/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8938 - loss: 0.1956 - val_accuracy: 0.8954 - val_loss: 0.1858\n",
      "Epoch 33/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8945 - loss: 0.1941 - val_accuracy: 0.9010 - val_loss: 0.1839\n",
      "Epoch 34/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8946 - loss: 0.1945 - val_accuracy: 0.8924 - val_loss: 0.1893\n",
      "Epoch 35/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8950 - loss: 0.1938 - val_accuracy: 0.8917 - val_loss: 0.1962\n",
      "Epoch 36/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8953 - loss: 0.1925 - val_accuracy: 0.8900 - val_loss: 0.1948\n",
      "Epoch 37/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8936 - loss: 0.1944 - val_accuracy: 0.8956 - val_loss: 0.1868\n",
      "Epoch 38/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8946 - loss: 0.1952 - val_accuracy: 0.8853 - val_loss: 0.1938\n",
      "Epoch 39/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8919 - loss: 0.1926 - val_accuracy: 0.8996 - val_loss: 0.1837\n",
      "Epoch 40/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8938 - loss: 0.1944 - val_accuracy: 0.8923 - val_loss: 0.1923\n",
      "Epoch 41/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8941 - loss: 0.1929 - val_accuracy: 0.9003 - val_loss: 0.1766\n",
      "Epoch 42/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8959 - loss: 0.1931 - val_accuracy: 0.8910 - val_loss: 0.1954\n",
      "Epoch 43/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8933 - loss: 0.1916 - val_accuracy: 0.9044 - val_loss: 0.1721\n",
      "Epoch 44/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8934 - loss: 0.1931 - val_accuracy: 0.8980 - val_loss: 0.1844\n",
      "Epoch 45/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8943 - loss: 0.1945 - val_accuracy: 0.8953 - val_loss: 0.1853\n",
      "Epoch 46/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8960 - loss: 0.1920 - val_accuracy: 0.8844 - val_loss: 0.1984\n",
      "Epoch 47/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8930 - loss: 0.1938 - val_accuracy: 0.8936 - val_loss: 0.1920\n",
      "Epoch 48/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8943 - loss: 0.1934 - val_accuracy: 0.8850 - val_loss: 0.1994\n",
      "Epoch 49/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8908 - loss: 0.1946 - val_accuracy: 0.9043 - val_loss: 0.1732\n",
      "Epoch 50/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8925 - loss: 0.1942 - val_accuracy: 0.8909 - val_loss: 0.1906\n",
      "Epoch 51/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8916 - loss: 0.1923 - val_accuracy: 0.9019 - val_loss: 0.1779\n",
      "Epoch 52/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8946 - loss: 0.1916 - val_accuracy: 0.8949 - val_loss: 0.1813\n",
      "Epoch 53/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8921 - loss: 0.1914 - val_accuracy: 0.8846 - val_loss: 0.1955\n",
      "Epoch 54/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8928 - loss: 0.1901 - val_accuracy: 0.8949 - val_loss: 0.1861\n",
      "Epoch 55/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8936 - loss: 0.1923 - val_accuracy: 0.8973 - val_loss: 0.1842\n",
      "Epoch 56/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8955 - loss: 0.1905 - val_accuracy: 0.8781 - val_loss: 0.2029\n",
      "Epoch 57/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8920 - loss: 0.1908 - val_accuracy: 0.8911 - val_loss: 0.1892\n",
      "Epoch 58/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8948 - loss: 0.1906 - val_accuracy: 0.8973 - val_loss: 0.1827\n",
      "Epoch 59/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8912 - loss: 0.1917 - val_accuracy: 0.8945 - val_loss: 0.1786\n",
      "Epoch 60/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8926 - loss: 0.1922 - val_accuracy: 0.8916 - val_loss: 0.1840\n",
      "Epoch 61/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8929 - loss: 0.1923 - val_accuracy: 0.8988 - val_loss: 0.1768\n",
      "Epoch 62/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8922 - loss: 0.1909 - val_accuracy: 0.8970 - val_loss: 0.1794\n",
      "Epoch 63/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8934 - loss: 0.1907 - val_accuracy: 0.9081 - val_loss: 0.1683\n",
      "Epoch 64/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8926 - loss: 0.1929 - val_accuracy: 0.8954 - val_loss: 0.1803\n",
      "Epoch 65/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8952 - loss: 0.1903 - val_accuracy: 0.8957 - val_loss: 0.1834\n",
      "Epoch 66/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8894 - loss: 0.1932 - val_accuracy: 0.8888 - val_loss: 0.1873\n",
      "Epoch 67/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8939 - loss: 0.1918 - val_accuracy: 0.8824 - val_loss: 0.2021\n",
      "Epoch 68/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8912 - loss: 0.1921 - val_accuracy: 0.8984 - val_loss: 0.1801\n",
      "Epoch 69/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8976 - loss: 0.1910 - val_accuracy: 0.9056 - val_loss: 0.1717\n",
      "Epoch 70/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8935 - loss: 0.1934 - val_accuracy: 0.8943 - val_loss: 0.1852\n",
      "Epoch 71/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8945 - loss: 0.1924 - val_accuracy: 0.8912 - val_loss: 0.1895\n",
      "Epoch 72/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8944 - loss: 0.1920 - val_accuracy: 0.8822 - val_loss: 0.1993\n",
      "Epoch 73/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8916 - loss: 0.1909 - val_accuracy: 0.8938 - val_loss: 0.1819\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 74/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8949 - loss: 0.1885 - val_accuracy: 0.8872 - val_loss: 0.2048\n",
      "Epoch 75/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8926 - loss: 0.1915 - val_accuracy: 0.8844 - val_loss: 0.1948\n",
      "Epoch 76/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8939 - loss: 0.1905 - val_accuracy: 0.8942 - val_loss: 0.1853\n",
      "Epoch 77/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8941 - loss: 0.1893 - val_accuracy: 0.8864 - val_loss: 0.1994\n",
      "Epoch 78/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8929 - loss: 0.1918 - val_accuracy: 0.8899 - val_loss: 0.1894\n",
      "Epoch 79/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8920 - loss: 0.1918 - val_accuracy: 0.8985 - val_loss: 0.1848\n",
      "Epoch 80/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8941 - loss: 0.1903 - val_accuracy: 0.8935 - val_loss: 0.1896\n",
      "Epoch 81/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8897 - loss: 0.1928 - val_accuracy: 0.9049 - val_loss: 0.1728\n",
      "Epoch 82/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8909 - loss: 0.1916 - val_accuracy: 0.9007 - val_loss: 0.1746\n",
      "Epoch 83/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8968 - loss: 0.1892 - val_accuracy: 0.8989 - val_loss: 0.1793\n",
      "Epoch 84/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8954 - loss: 0.1901 - val_accuracy: 0.8891 - val_loss: 0.1916\n",
      "Epoch 85/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8940 - loss: 0.1886 - val_accuracy: 0.8882 - val_loss: 0.1929\n",
      "Epoch 86/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8941 - loss: 0.1887 - val_accuracy: 0.8920 - val_loss: 0.1895\n",
      "Epoch 87/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8956 - loss: 0.1888 - val_accuracy: 0.8940 - val_loss: 0.1939\n",
      "Epoch 88/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8931 - loss: 0.1906 - val_accuracy: 0.8966 - val_loss: 0.1818\n",
      "Epoch 89/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8924 - loss: 0.1909 - val_accuracy: 0.9010 - val_loss: 0.1777\n",
      "Epoch 90/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8954 - loss: 0.1912 - val_accuracy: 0.8902 - val_loss: 0.1897\n",
      "Epoch 91/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8916 - loss: 0.1900 - val_accuracy: 0.8778 - val_loss: 0.2065\n",
      "Epoch 92/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8921 - loss: 0.1900 - val_accuracy: 0.8931 - val_loss: 0.1896\n",
      "Epoch 93/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8921 - loss: 0.1898 - val_accuracy: 0.8879 - val_loss: 0.1912\n",
      "Epoch 94/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8952 - loss: 0.1886 - val_accuracy: 0.8910 - val_loss: 0.1870\n",
      "Epoch 95/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8950 - loss: 0.1912 - val_accuracy: 0.8917 - val_loss: 0.1824\n",
      "Epoch 96/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8917 - loss: 0.1893 - val_accuracy: 0.8886 - val_loss: 0.1887\n",
      "Epoch 97/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8928 - loss: 0.1910 - val_accuracy: 0.8865 - val_loss: 0.1886\n",
      "Epoch 98/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8929 - loss: 0.1895 - val_accuracy: 0.8888 - val_loss: 0.1900\n",
      "Epoch 99/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8918 - loss: 0.1869 - val_accuracy: 0.8938 - val_loss: 0.1817\n",
      "Epoch 100/100\n",
      "893/893 - 3s - 3ms/step - accuracy: 0.8930 - loss: 0.1902 - val_accuracy: 0.8949 - val_loss: 0.1858\n"
     ]
    }
   ],
   "source": [
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "import numpy as np\n",
    "\n",
    "# Compute class weights for balanced training\n",
    "class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(Y_train), y=Y_train)\n",
    "class_weight_dict = dict(enumerate(class_weights))\n",
    "\n",
    "# Retrain model with class weights\n",
    "history = model.fit(\n",
    "    X_train, Y_train,\n",
    "    epochs=100, \n",
    "    batch_size=64,\n",
    "    validation_split=0.2,\n",
    "    verbose=2,\n",
    "    class_weight=class_weight_dict\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2c490027",
   "metadata": {},
   "source": [
    "#### Architecture Refinement"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "ec5a92a9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py:205: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.\n",
      "  super().__init__(**kwargs)\n"
     ]
    }
   ],
   "source": [
    "from tensorflow.keras.layers import Dropout\n",
    "\n",
    "model = Sequential()\n",
    "model.add(LSTM(50, input_shape=(X_train.shape[1], X_train.shape[2]), return_sequences=True))\n",
    "model.add(Dropout(0.2))  # Dropout layer\n",
    "model.add(LSTM(50, return_sequences=False))\n",
    "model.add(Dropout(0.2))  # Another Dropout layer\n",
    "model.add(Dense(1, activation='sigmoid'))\n",
    "\n",
    "model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', Precision(), Recall()])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "52f533c0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "558/558 - 1s - 3ms/step - accuracy: 0.4667 - loss: 0.6928 - precision_1: 0.0581 - recall_1: 0.4006\n",
      "Refined Model Test Accuracy: 46.67%\n",
      "Refined Model Precision: 0.06\n",
      "Refined Model Recall: 0.40\n",
      "\u001b[1m558/558\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m1s\u001b[0m 1ms/step\n",
      "Refined Model F1 Score: 0.10\n",
      "Refined Model ROC AUC Score: 0.42\n"
     ]
    }
   ],
   "source": [
    "# Evaluate the refined model on the test set\n",
    "loss, accuracy, precision, recall = model.evaluate(X_test, Y_test, verbose=2)\n",
    "print(f'Refined Model Test Accuracy: {accuracy*100:.2f}%')\n",
    "print(f'Refined Model Precision: {precision:.2f}')\n",
    "print(f'Refined Model Recall: {recall:.2f}')\n",
    "\n",
    "# Calculate and print F1 score and ROC AUC for the refined model\n",
    "y_probs_refined = model.predict(X_test)[:, 0]  # assuming your model outputs probabilities for class 1\n",
    "y_pred_refined = (y_probs_refined > 0.5).astype('int32')\n",
    "\n",
    "# F1 Score\n",
    "f1_refined = f1_score(Y_test, y_pred_refined)\n",
    "print(f'Refined Model F1 Score: {f1_refined:.2f}')\n",
    "\n",
    "# ROC AUC Score\n",
    "roc_auc_refined = roc_auc_score(Y_test, y_probs_refined)\n",
    "print(f'Refined Model ROC AUC Score: {roc_auc_refined:.2f}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0678cd8a",
   "metadata": {},
   "source": [
    "#### Hyperparameter Tuning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "355ab2a6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: tensorflow in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (2.16.1)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (1.2.0)\n",
      "Requirement already satisfied: packaging in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (21.3)\n",
      "Requirement already satisfied: keras>=3.0.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow) (3.0.5)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (4.3.0)\n",
      "Requirement already satisfied: tensorboard<2.17,>=2.16 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow) (2.16.2)\n",
      "Requirement already satisfied: six>=1.12.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (1.16.0)\n",
      "Requirement already satisfied: flatbuffers>=23.5.26 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow) (24.3.7)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (0.2.0)\n",
      "Requirement already satisfied: ml-dtypes~=0.3.1 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow) (0.3.2)\n",
      "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (0.4.0)\n",
      "Requirement already satisfied: setuptools in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (58.1.0)\n",
      "Requirement already satisfied: h5py>=3.10.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow) (3.10.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (1.6.3)\n",
      "Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow) (1.26.4)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (0.26.0)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (3.3.0)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (2.28.0)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow) (4.25.3)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (1.14.1)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorflow) (1.62.1)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (14.0.6)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorflow) (1.1.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow) (0.37.1)\n",
      "Requirement already satisfied: dm-tree in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras>=3.0.0->tensorflow) (0.1.8)\n",
      "Requirement already satisfied: rich in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras>=3.0.0->tensorflow) (13.7.1)\n",
      "Requirement already satisfied: namex in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras>=3.0.0->tensorflow) (0.0.7)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (1.26.9)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (2022.5.18.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (3.3)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (2.0.12)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow) (0.7.2)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow) (2.2.1)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow) (3.4.1)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from packaging->tensorflow) (3.0.9)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow) (2.1.1)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from rich->keras>=3.0.0->tensorflow) (3.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from rich->keras>=3.0.0->tensorflow) (2.16.1)\n",
      "Requirement already satisfied: mdurl~=0.1 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow) (0.1.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install --upgrade tensorflow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9b745fa7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting keras-tuner\n",
      "  Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m129.1/129.1 KB\u001b[0m \u001b[31m985.2 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: packaging in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from keras-tuner) (21.3)\n",
      "Requirement already satisfied: requests in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from keras-tuner) (2.28.0)\n",
      "Collecting kt-legacy\n",
      "  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)\n",
      "Requirement already satisfied: keras in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras-tuner) (3.0.5)\n",
      "Requirement already satisfied: ml-dtypes in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras->keras-tuner) (0.3.2)\n",
      "Requirement already satisfied: rich in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras->keras-tuner) (13.7.1)\n",
      "Requirement already satisfied: h5py in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras->keras-tuner) (3.10.0)\n",
      "Requirement already satisfied: dm-tree in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras->keras-tuner) (0.1.8)\n",
      "Requirement already satisfied: absl-py in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from keras->keras-tuner) (1.2.0)\n",
      "Requirement already satisfied: numpy in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras->keras-tuner) (1.26.4)\n",
      "Requirement already satisfied: namex in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from keras->keras-tuner) (0.0.7)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from packaging->keras-tuner) (3.0.9)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from requests->keras-tuner) (3.3)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from requests->keras-tuner) (1.26.9)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from requests->keras-tuner) (2022.5.18.1)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from requests->keras-tuner) (2.0.12)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /geode2/soft/hps/sles15/python/gnu/3.10.5/lib/python3.10/site-packages (from rich->keras->keras-tuner) (2.16.1)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from rich->keras->keras-tuner) (3.0.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /geode2/home/u070/rajaali/BigRed200/.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)\n",
      "Installing collected packages: kt-legacy, keras-tuner\n",
      "Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5\n"
     ]
    }
   ],
   "source": [
    "!pip install keras-tuner"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "fce90989-d337-450e-b1e7-a060d1e98c6a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting tensorflow-gpu\n",
      "  Downloading tensorflow-gpu-2.12.0.tar.gz (2.6 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[39 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/_vendor/packaging/requirements.py\", line 35, in __init__\n",
      "  \u001b[31m   \u001b[0m     parsed = parse_requirement(requirement_string)\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py\", line 64, in parse_requirement\n",
      "  \u001b[31m   \u001b[0m     return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py\", line 82, in _parse_requirement\n",
      "  \u001b[31m   \u001b[0m     url, specifier, marker = _parse_requirement_details(tokenizer)\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py\", line 126, in _parse_requirement_details\n",
      "  \u001b[31m   \u001b[0m     marker = _parse_requirement_marker(\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py\", line 147, in _parse_requirement_marker\n",
      "  \u001b[31m   \u001b[0m     tokenizer.raise_syntax_error(\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/_vendor/packaging/_tokenizer.py\", line 163, in raise_syntax_error\n",
      "  \u001b[31m   \u001b[0m     raise ParserSyntaxError(\n",
      "  \u001b[31m   \u001b[0m setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)\n",
      "  \u001b[31m   \u001b[0m     python_version>\"3.7\"\n",
      "  \u001b[31m   \u001b[0m                   ^\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m The above exception was the direct cause of the following exception:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-vlgghm6m/tensorflow-gpu_33d40ad749884172a75f683f3f9cb68f/setup.py\", line 40, in <module>\n",
      "  \u001b[31m   \u001b[0m     setuptools.setup()\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/__init__.py\", line 107, in setup\n",
      "  \u001b[31m   \u001b[0m     _install_setup_requires(attrs)\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/__init__.py\", line 78, in _install_setup_requires\n",
      "  \u001b[31m   \u001b[0m     dist.parse_config_files(ignore_option_errors=True)\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/dist.py\", line 887, in parse_config_files\n",
      "  \u001b[31m   \u001b[0m     self._finalize_requires()\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/dist.py\", line 594, in _finalize_requires\n",
      "  \u001b[31m   \u001b[0m     self._move_install_requirements_markers()\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/dist.py\", line 634, in _move_install_requirements_markers\n",
      "  \u001b[31m   \u001b[0m     inst_reqs = list(_reqs.parse(spec_inst_reqs))\n",
      "  \u001b[31m   \u001b[0m   File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/site-packages/setuptools/_vendor/packaging/requirements.py\", line 37, in __init__\n",
      "  \u001b[31m   \u001b[0m     raise InvalidRequirement(str(e)) from e\n",
      "  \u001b[31m   \u001b[0m setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)\n",
      "  \u001b[31m   \u001b[0m     python_version>\"3.7\"\n",
      "  \u001b[31m   \u001b[0m                   ^\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.0\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip3 install --upgrade pip\u001b[0m\n",
      "\u001b[?25hNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install --upgrade tensorflow-gpu"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "04d71870",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reloading Tuner from my_dir/diabetes_prediction/tuner0.json\n",
      "\n",
      "Search: Running Trial #4\n",
      "\n",
      "Value             |Best Value So Far |Hyperparameter\n",
      "480               |256               |units\n",
      "0.4               |0.1               |dropout\n",
      "\n",
      "Epoch 1/10\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n",
      "    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n",
      "    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n",
      "    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n",
      "    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n",
      "    return model.fit(*args, **kwargs)\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 123, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n",
      "\n",
      "Detected at node sequential_1/lstm_1/CudnnRNN defined at (most recent call last):\n",
      "  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "\n",
      "  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "\n",
      "  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "\n",
      "  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "\n",
      "  File \"/tmp/ipykernel_114307/3980510444.py\", line 30, in <module>\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 323, in fit\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 117, in one_step_on_iterator\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 105, in one_step_on_data\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 56, in train_step\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 816, in __call__\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 42, in __call__\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 157, in error_handler\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 203, in call\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/models/functional.py\", line 188, in call\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/ops/function.py\", line 153, in _run_through_graph\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/models/functional.py\", line 572, in call\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 816, in __call__\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 42, in __call__\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 157, in error_handler\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/lstm.py\", line 538, in call\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py\", line 397, in call\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/lstm.py\", line 512, in inner_loop\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/rnn.py\", line 822, in lstm\n",
      "\n",
      "  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/rnn.py\", line 933, in _cudnn_lstm\n",
      "\n",
      "Dnn is not supported\n",
      "\t [[{{node sequential_1/lstm_1/CudnnRNN}}]] [Op:__inference_one_step_on_iterator_10737]\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Number of consecutive failures exceeded the limit of 3.\nTraceback (most recent call last):\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 123, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node sequential_1/lstm_1/CudnnRNN defined at (most recent call last):\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/tmp/ipykernel_114307/3980510444.py\", line 30, in <module>\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 323, in fit\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 117, in one_step_on_iterator\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 105, in one_step_on_data\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 56, in train_step\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 816, in __call__\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 42, in __call__\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 157, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 203, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/models/functional.py\", line 188, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/ops/function.py\", line 153, in _run_through_graph\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/models/functional.py\", line 572, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 816, in __call__\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 42, in __call__\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 157, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/lstm.py\", line 538, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py\", line 397, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/lstm.py\", line 512, in inner_loop\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/rnn.py\", line 822, in lstm\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/rnn.py\", line 933, in _cudnn_lstm\n\nDnn is not supported\n\t [[{{node sequential_1/lstm_1/CudnnRNN}}]] [Op:__inference_one_step_on_iterator_10737]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[11], line 30\u001b[0m\n\u001b[1;32m     19\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m model\n\u001b[1;32m     21\u001b[0m tuner \u001b[38;5;241m=\u001b[39m RandomSearch(\n\u001b[1;32m     22\u001b[0m     build_model,\n\u001b[1;32m     23\u001b[0m     objective\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mval_accuracy\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     27\u001b[0m     project_name\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mdiabetes_prediction\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m     28\u001b[0m )\n\u001b[0;32m---> 30\u001b[0m \u001b[43mtuner\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msearch\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mY_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m10\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mX_test\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mY_test\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     31\u001b[0m best_model \u001b[38;5;241m=\u001b[39m tuner\u001b[38;5;241m.\u001b[39mget_best_models(num_models\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m1\u001b[39m)[\u001b[38;5;241m0\u001b[39m]\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py:235\u001b[0m, in \u001b[0;36mBaseTuner.search\u001b[0;34m(self, *fit_args, **fit_kwargs)\u001b[0m\n\u001b[1;32m    233\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mon_trial_begin(trial)\n\u001b[1;32m    234\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_try_run_and_update_trial(trial, \u001b[38;5;241m*\u001b[39mfit_args, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mfit_kwargs)\n\u001b[0;32m--> 235\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mon_trial_end\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrial\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    236\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mon_search_end()\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py:339\u001b[0m, in \u001b[0;36mBaseTuner.on_trial_end\u001b[0;34m(self, trial)\u001b[0m\n\u001b[1;32m    333\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mon_trial_end\u001b[39m(\u001b[38;5;28mself\u001b[39m, trial):\n\u001b[1;32m    334\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Called at the end of a trial.\u001b[39;00m\n\u001b[1;32m    335\u001b[0m \n\u001b[1;32m    336\u001b[0m \u001b[38;5;124;03m    Args:\u001b[39;00m\n\u001b[1;32m    337\u001b[0m \u001b[38;5;124;03m        trial: A `Trial` instance.\u001b[39;00m\n\u001b[1;32m    338\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 339\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moracle\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mend_trial\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrial\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    340\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msave()\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/keras_tuner/src/engine/oracle.py:108\u001b[0m, in \u001b[0;36msynchronized.<locals>.wrapped_func\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    106\u001b[0m     LOCKS[oracle]\u001b[38;5;241m.\u001b[39macquire()\n\u001b[1;32m    107\u001b[0m     THREADS[oracle] \u001b[38;5;241m=\u001b[39m thread_name\n\u001b[0;32m--> 108\u001b[0m ret_val \u001b[38;5;241m=\u001b[39m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    109\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m need_acquire:\n\u001b[1;32m    110\u001b[0m     THREADS[oracle] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/keras_tuner/src/engine/oracle.py:588\u001b[0m, in \u001b[0;36mOracle.end_trial\u001b[0;34m(self, trial)\u001b[0m\n\u001b[1;32m    586\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_retry(trial):\n\u001b[1;32m    587\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mend_order\u001b[38;5;241m.\u001b[39mappend(trial\u001b[38;5;241m.\u001b[39mtrial_id)\n\u001b[0;32m--> 588\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_check_consecutive_failures\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    590\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_save_trial(trial)\n\u001b[1;32m    591\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msave()\n",
      "File \u001b[0;32m~/.local/lib/python3.10/site-packages/keras_tuner/src/engine/oracle.py:545\u001b[0m, in \u001b[0;36mOracle._check_consecutive_failures\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    543\u001b[0m     consecutive_failures \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[1;32m    544\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m consecutive_failures \u001b[38;5;241m==\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmax_consecutive_failed_trials:\n\u001b[0;32m--> 545\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\n\u001b[1;32m    546\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mNumber of consecutive failures exceeded the limit \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    547\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mof \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmax_consecutive_failed_trials\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    548\u001b[0m         \u001b[38;5;241m+\u001b[39m (trial\u001b[38;5;241m.\u001b[39mmessage \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    549\u001b[0m     )\n",
      "\u001b[0;31mRuntimeError\u001b[0m: Number of consecutive failures exceeded the limit of 3.\nTraceback (most recent call last):\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 123, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node sequential_1/lstm_1/CudnnRNN defined at (most recent call last):\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/N/soft/sles15/deeplearning/Python-3.10.10/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/tmp/ipykernel_114307/3980510444.py\", line 30, in <module>\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 323, in fit\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 117, in one_step_on_iterator\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 105, in one_step_on_data\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 56, in train_step\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 816, in __call__\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 42, in __call__\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 157, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 203, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/models/functional.py\", line 188, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/ops/function.py\", line 153, in _run_through_graph\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/models/functional.py\", line 572, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 816, in __call__\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 118, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 42, in __call__\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 157, in error_handler\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/lstm.py\", line 538, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py\", line 397, in call\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/layers/rnn/lstm.py\", line 512, in inner_loop\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/rnn.py\", line 822, in lstm\n\n  File \"/N/u/rajaali/BigRed200/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/rnn.py\", line 933, in _cudnn_lstm\n\nDnn is not supported\n\t [[{{node sequential_1/lstm_1/CudnnRNN}}]] [Op:__inference_one_step_on_iterator_10737]\n"
     ]
    }
   ],
   "source": [
    "from keras_tuner import RandomSearch\n",
    "from tensorflow.keras import Sequential\n",
    "from tensorflow.keras.layers import LSTM, Dropout, Dense\n",
    "from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint\n",
    "\n",
    "\n",
    "\n",
    "def build_model(hp):\n",
    "    model = Sequential()\n",
    "    model.add(LSTM(units=hp.Int('units', min_value=32, max_value=512, step=32),\n",
    "                   input_shape=(X_train.shape[1], X_train.shape[2]),\n",
    "                   return_sequences=True))\n",
    "    model.add(Dropout(rate=hp.Float('dropout', min_value=0.0, max_value=0.5, step=0.1)))\n",
    "    model.add(LSTM(units=hp.Int('units', min_value=32, max_value=512, step=32)))\n",
    "    model.add(Dropout(rate=hp.Float('dropout', min_value=0.0, max_value=0.5, step=0.1)))\n",
    "    model.add(Dense(1, activation='sigmoid'))\n",
    "    \n",
    "    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])\n",
    "    return model\n",
    "\n",
    "tuner = RandomSearch(\n",
    "    build_model,\n",
    "    objective='val_accuracy',\n",
    "    max_trials=10,\n",
    "    executions_per_trial=3,\n",
    "    directory='my_dir',\n",
    "    project_name='diabetes_prediction'\n",
    ")\n",
    "\n",
    "tuner.search(X_train, Y_train, epochs=10, validation_data=(X_test, Y_test))\n",
    "best_model = tuner.get_best_models(num_models=1)[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "123f516f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import roc_curve, precision_recall_curve, auc\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ROC Curve\n",
    "y_probs = best_model.predict(X_test)[:, 0]\n",
    "fpr, tpr, thresholds = roc_curve(Y_test, y_probs)\n",
    "roc_auc = auc(fpr, tpr)\n",
    "\n",
    "plt.figure()\n",
    "plt.plot(fpr, tpr, label=f'ROC curve (area = {roc_auc:.2f})')\n",
    "plt.plot([0, 1], [0, 1], 'k--')\n",
    "plt.xlim([0.0, 1.0])\n",
    "plt.ylim([0.0, 1.05])\n",
    "plt.xlabel('False Positive Rate')\n",
    "plt.ylabel('True Positive Rate')\n",
    "plt.title('Receiver Operating Characteristic')\n",
    "plt.legend(loc=\"lower right\")\n",
    "plt.show()\n",
    "\n",
    "# Precision-Recall Curve\n",
    "precision, recall, _ = precision_recall_curve(Y_test, y_probs)\n",
    "pr_auc = auc(recall, precision)\n",
    "\n",
    "plt.figure()\n",
    "plt.plot(recall, precision, label=f'PR curve (area = {pr_auc:.2f})')\n",
    "plt.xlabel('Recall')\n",
    "plt.ylabel('Precision')\n",
    "plt.title('Precision-Recall Curve')\n",
    "plt.legend(loc=\"upper right\")\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
